# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://zhanglaiya.github.io"
title: zhanglaiya
copyright: "© [zhanglaiya](https://github.com/zhanglaiya)"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["post", "papermod"]
defaultContentLanguage: zh

minify:
  disableXML: true
  # minifyOutput: true

languages:
  zh:
    languageName: "中文"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: 搜索
          url: search/
          weight: 10
        - name: 标签
          url: tags/
          weight: 10
        - name: 源码
          url: https://github.com/zhanglaiya/zhanglaiya.github.io

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "zhanglaiya's blog - https://github.com/zhanglaiya/zhanglaiya.github.io"
  author: zhanglaiya
  # author: ["Me", "You"] # multiple authors
  # math: true
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "zhanglaiya's Blog"
    Content: >
      👋 Hi, 我是zhanglaiya, 一个爱好JavaScript, Python的爬虫开发。

      - 下面是我做的一些开源项目
      
      - [Pyttyd](https://github.com/zhanglaiya/pyttyd) python开发的终端分享工具
      
      - [deconfuse](https://deconfuse.pages.dev/) js解混淆工具

      - 如果对我的项目感兴趣, 麻烦在GitHub点个🌟, 非常感谢！

      - 现在在学前端 [React](https://zh-hans.react.dev/learn) & [Nextjs](https://nextjs.org/docs).

      - 博客用于分享学习技术和记录个人生活, 不作任何商业用途, 如有侵权请联系我 315396460@qq.com

  socialIcons:
    - name: github
      title: Github源码
      url: "https://github.com/zhanglaiya/zhanglaiya.github.io"
    - name: qq
      title: QQ
    - name: wechat
      title: 微信
    - name: bilibili
      title: b站

  editPost:
    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true